### ISSUE TITLE
how to predict an image after training?

### ISSUE THREAD

**Issue by leolle** [Deepayan137/Adapting-OCR#18]
Hi, I trained the model using your code on my dataset, how to predict an image beyond the dataset?

**Comment by Deepayan137** [comment]
Hello, please see the test.py script. You will have to adjust the command line arguments as per your need. Also, you can have a look at the Evaluation section in this  [notebook](https://github.com/Deepayan137/Adapting-OCR/blob/master/notebooks/ocr.ipynb).

**Comment by leolle** [comment]
Thank you.
I have a problem of overfitting, the trained model can only recognize specific fonts and font size, how do you solve this problem?

**Comment by Deepayan137** [comment]
One way to solve this would be to use various fonts while training. You can also experiment with adding Gaussian noise and various other augmentations. The idea is to show the model a lot of variations to generalise well to test samples. You can also try labelling a few hundred test samples and fine-tune the model on them. Your problem seems to mainly stem from the data distribution shift. There are works that try to address them. You can go through our paper (link in the GitHub readme) to understand how such things are typically handled.

**Comment by leolle** [comment]
Fine-tuning sounds interesting. Is this part included in your code?

**Comment by Deepayan137** [comment]
Yes, please take a look at the `train_semi_supervised.py` script.
