### ISSUE TITLE
U are almost trash

### ISSUE THREAD

**Issue by WilledgeR** [Deepayan137/Adapting-OCR#30]
after setting all the sheet up! it requires pytorch_pretrained_bert.

u as the writer are almost garbage

**Comment by Deepayan137** [comment]
Hello, thank you for the kind feedback. I have updated the requirements file and the readme regarding the `pytorch_pretrained_bert` package. Please have a look. Also, since you have already downloaded all the packages mentioned in the `requirements.txt`, adding one more package won't be much trouble. Please do a `pip install pytorch_pretrained_bert`. Again, sorry for the inconvenience caused and thank you for pointing out the error. Have a nice day :)

**Comment by WilledgeR** [comment]
I've never thought u answer this issue :)

thank you and sorry by the way.
